/* ============================================================
   GO.VARLIN — COURSE DATA
   Single source of truth for every program's curriculum,
   used by course-details.html (and available to index.html).
   ============================================================ */

const SITE_DATA = {
  audience: [
    { icon:'🎓', label:'Freshers', desc:'Start from the fundamentals — zero prior coding experience needed.' },
    { icon:'📘', label:'College Students', desc:'Build job-ready skills alongside your degree, at your own pace.' },
    { icon:'💼', label:'Working Professionals', desc:'Upskill on evenings & weekends without pausing your career.' },
    { icon:'🔄', label:'Career Switchers', desc:'Pivot into tech with a structured, mentor-guided roadmap.' }
  ],
  aiTools: ['ChatGPT','GitHub Copilot','Claude','Gemini','LangChain','LangGraph','OpenAI API','Pinecone','FAISS','Ollama','HuggingFace','Prompt Engineering'],
  certification: {
    title: 'Industry Recognized Certificate',
    points: ['Official Certification','Lifetime Valid','Project Based','Resume Ready','LinkedIn Shareable']
  },
  hiringPartners: ['Amazon','Infosys','TCS','Accenture','Capgemini','Wipro','Cognizant','Deloitte','IBM','Oracle','Microsoft','Google','Tech Mahindra','HCL','Persistent','Zeta','KPMG','Empuraan'],
  placementFeatures: [
    { icon:'📄', label:'Resume Building' }, { icon:'🔗', label:'LinkedIn Optimization' },
    { icon:'🎤', label:'Mock Interviews' }, { icon:'🧪', label:'Weekly Coding Tests' },
    { icon:'🗣️', label:'HR Preparation' }, { icon:'💻', label:'Technical Interviews' },
    { icon:'🗂️', label:'Portfolio Reviews' }, { icon:'🤝', label:'Referral Support' },
    { icon:'🧭', label:'Career Guidance' }
  ],
  whyChooseUs: [
    { icon:'👨‍🏫', label:'Industry Experts' }, { icon:'🎥', label:'Live Classes' }, { icon:'📼', label:'Recorded Classes' },
    { icon:'♾️', label:'Lifetime Access' }, { icon:'🛠️', label:'Real Projects' }, { icon:'📝', label:'Assignments' },
    { icon:'📊', label:'Weekly Tests' }, { icon:'💬', label:'Doubt Support' }, { icon:'🌐', label:'Community Access' },
    { icon:'🎯', label:'Internship Support' }, { icon:'🚀', label:'Placement Assistance' }, { icon:'🗣️', label:'Interview Preparation' }
  ],
  learningJourney: ['Enroll','Learn','Assignments','Projects','Internship','Mock Interviews','Placement'],
  studentBenefits: [
    { icon:'♾️', label:'Lifetime LMS Access' }, { icon:'📓', label:'Notes' }, { icon:'🎬', label:'Recorded Videos' },
    { icon:'📝', label:'Assignments' }, { icon:'🧩', label:'Coding Challenges' }, { icon:'💾', label:'Source Code' },
    { icon:'📜', label:'Certificates' }, { icon:'🧭', label:'Career Support' }
  ]
};

const COURSE_DATA = {

  "full-stack-java": {
    category: "Development",
    name: "Full Stack Java",
    headerLabel: "JAVA FULL STACK",
    tagline: "Development Program",
    icon: "🧩",
    duration: "5 Months",
    eligibility: "Any Branch",
    batchStatus: "Batch Open",
    language: "English & Hindi",
    batchStarts: "3rd Aug 2026",
    genAI: true,
    headerRating: 4.9,
    headerStudents: "1500+",
    headerPlacement: "100% Placement Assistance",
    projects: "10 Projects",
    level: "Beginner → Job Ready",
    price: 30000,
    originalPrice: 59999,
    rating: 4.9,
    reviews: 2840,
    students: 12450,
    badge: "Bestseller",
    brochure: "full-stack-java-brochure",
    certificateImage: "certificates/full-stack-java.png",
    description: "Java, Spring Boot, Hibernate and React, taught the way product teams actually build — end to end, from schema to deployment, with Gen AI woven through every phase.",
    chips: ["Java", "Spring Boot", "Hibernate", "MySQL", "HTML", "CSS", "JavaScript", "React", "Git", "GitHub", "Deployment"],
    jobRoles: ["Java Developer","Backend Developer","Spring Boot Developer","Full Stack Developer","Software Engineer"],
    modules: [
      { title: "Programming Foundations", weeks: "Weeks 1–4", topics: ["Programming Basics","Logic Building","Flowcharts","Algorithms","Java Basics","Git & GitHub","Mini Projects","Interview Preparation"] },
      { title: "Core Java", weeks: "Weeks 5–8", topics: ["Core Java","OOP","Collections","Exception Handling","File Handling","Multithreading","JDBC","Java Projects"] },
      { title: "Backend Engineering", weeks: "Weeks 9–12", topics: ["SQL","MySQL","Spring","Spring Boot","REST APIs","Hibernate","Authentication","Backend Deployment"] },
      { title: "Frontend Engineering", weeks: "Weeks 13–16", topics: ["HTML","CSS","JavaScript","Bootstrap","React","Redux","API Integration","Responsive Websites"] },
      { title: "Capstone & Placement Prep", weeks: "Weeks 17–20", topics: ["Capstone Project","AI Integration","Resume Building","LinkedIn Optimization","Mock Interviews","Placement Preparation","Portfolio","Deployment"] }
    ],
    toolsCovered: ["Java","Spring","Spring Boot","Hibernate","MySQL","Postman","Git","GitHub","VS Code","IntelliJ IDEA","HTML","CSS","JavaScript","Bootstrap","React","Redux","Docker","AWS","Render","Vercel","Netlify"],
    skills: ["Java Programming","Object Oriented Programming","Backend Development","REST APIs","Database Design","Frontend Development","React","Authentication","JWT","Spring Security","Deployment","Version Control","AI Integration","Prompt Engineering","Problem Solving","Interview Skills"],
    realProjects: [
      { name:"Food Delivery App", tags:["Java","Spring Boot","MySQL"] },
      { name:"E-Commerce Website", tags:["React","Spring Boot","REST API"] },
      { name:"Employee Management", tags:["Java","Hibernate","MySQL"] },
      { name:"Hospital Management", tags:["Spring Boot","MySQL","JWT"] },
      { name:"Chat Application", tags:["Java","WebSockets","React"] },
      { name:"Banking Application", tags:["Spring Security","MySQL","JWT"] },
      { name:"AI Resume Builder", tags:["React","OpenAI API","Spring Boot"] },
      { name:"AI Chatbot", tags:["LangChain","Java","REST API"] },
      { name:"Task Management System", tags:["React","Redux","Spring Boot"] },
      { name:"Portfolio Website", tags:["HTML","CSS","JavaScript"] }
    ],
    faqs: [
      { q:"Who is the Full Stack Java program for?", a:"Freshers, college students, working professionals and career switchers with no prior backend or frontend experience required — we start from programming fundamentals." },
      { q:"Do I need prior coding knowledge?", a:"No. The first 4 weeks cover programming basics, logic building and flowcharts before we move into Java." },
      { q:"Is this course beginner friendly?", a:"Yes — the entire 20-week path is designed to take an absolute beginner to a job-ready full stack Java developer." },
      { q:"What will I learn in this program?", a:"Core Java, OOP, Spring, Spring Boot, Hibernate, MySQL, REST APIs, HTML, CSS, JavaScript, React and Redux — plus Gen AI integration." },
      { q:"Is Gen AI really included?", a:"Yes. You'll use ChatGPT, GitHub Copilot, Claude, Gemini, LangChain and more throughout the course, and build an AI-integrated capstone." },
      { q:"How long is the course?", a:"5 months (20 weeks), delivered in structured phases with weekly milestones." },
      { q:"Will I build real projects?", a:"Yes — 10 real-world projects including an e-commerce site, banking application, AI resume builder and AI chatbot." },
      { q:"Is there placement assistance?", a:"Yes, 100% placement assistance including resume building, mock interviews, referrals and career guidance." },
      { q:"Do I get a certificate?", a:"Yes — an industry recognized, project-based, lifetime-valid certificate that's resume ready and LinkedIn shareable." },
      { q:"What tools will I use?", a:"Java, Spring Boot, Hibernate, MySQL, Postman, Git, GitHub, VS Code, IntelliJ IDEA, React, Docker, AWS and more." },
      { q:"Is the batch currently open?", a:"Yes, the next batch is open for enrollment. Seats are limited to keep mentor-to-student ratio high." },
      { q:"What is the eligibility criteria?", a:"Open to students from any branch — no specific degree or background is required." },
      { q:"Do you offer EMI or installment options?", a:"Yes, flexible payment plans are available. Talk to a counselor for the options that fit you." },
      { q:"What kind of support will I get if I'm stuck?", a:"Dedicated doubt support, weekly mentor reviews and an active peer community throughout the program." }
    ]
  },

  "full-stack-python": {
    category: "Development",
    name: "Full Stack Python",
    headerLabel: "PYTHON FULL STACK",
    tagline: "Development Program",
    icon: "🐍",
    duration: "6 Months",
    eligibility: "Any Branch",
    batchStatus: "Batch Open",
    language: "English & Hindi",
    batchStarts: "10th Aug 2026",
    genAI: true,
    headerRating: 4.8,
    headerStudents: "1200+",
    headerPlacement: "100% Placement Assistance",
    projects: "10 Projects",
    level: "Beginner Friendly",
    price: 30000,
    originalPrice: 59999,
    rating: 4.6,
    reviews: 2115,
    students: 9870,
    badge: "Beginner Friendly",
    brochure: "full-stack-python-brochure",
    certificateImage: "certificates/full-stack-python.png",
    demoVideo: "static/videos/full-stack-python-demo.mp4",
    description: "Django, Flask and REST APIs on the backend, paired with a modern React front end — a complete, deployable product stack, with Gen AI integrated end to end.",
    chips: ["Python", "Django", "Flask", "REST API", "MySQL", "MongoDB", "HTML", "CSS", "JavaScript", "React", "Deployment"],
    jobRoles: ["Python Developer","Backend Developer","Django Developer","Full Stack Developer","Software Engineer"],
    modules: [
      { title: "Python Foundations", weeks: "Weeks 1–4", topics: ["Python syntax & data structures", "OOP in Python", "File handling & modules", "Working with databases", "Git & GitHub", "Mini Projects"] },
      { title: "Backend with Django & Flask", weeks: "Weeks 5–9", topics: ["Django ORM & models", "REST API design", "Flask microservices", "Authentication & sessions"] },
      { title: "Databases", weeks: "Weeks 10–12", topics: ["MySQL relational design", "MongoDB & NoSQL basics", "Query optimization"] },
      { title: "Frontend with React", weeks: "Weeks 13–17", topics: ["HTML5, CSS3 & responsive layout", "Modern JavaScript (ES6+)", "React components & hooks", "State management"] },
      { title: "Capstone & Placement Prep", weeks: "Weeks 18–24", topics: ["AI Integration","Full stack capstone project", "Cloud deployment", "Resume & interview preparation", "Mock interviews"] }
    ],
    toolsCovered: ["Python","Django","Flask","MySQL","MongoDB","Postman","Git","GitHub","VS Code","PyCharm","HTML","CSS","JavaScript","React","Docker","AWS","Render","Vercel","Netlify"],
    skills: ["Python Programming","Object Oriented Programming","Backend Development","REST APIs","Database Design","Frontend Development","React","Authentication","JWT","Deployment","Version Control","AI Integration","Prompt Engineering","Problem Solving","Interview Skills"],
    realProjects: [
      { name:"E-Commerce Website", tags:["Django","React","MySQL"] },
      { name:"Food Delivery App", tags:["Flask","React","MongoDB"] },
      { name:"Employee Management", tags:["Django","MySQL"] },
      { name:"Hospital Management", tags:["Django","REST API"] },
      { name:"Chat Application", tags:["Python","WebSockets"] },
      { name:"AI Resume Builder", tags:["React","OpenAI API","Flask"] },
      { name:"AI Chatbot", tags:["LangChain","Python"] },
      { name:"Task Management System", tags:["React","Django"] },
      { name:"Blogging Platform", tags:["Django","MySQL"] },
      { name:"Portfolio Website", tags:["HTML","CSS","JavaScript"] }
    ],
    faqs: [
      { q:"Who is the Full Stack Python program for?", a:"Freshers, college students, working professionals and career switchers — no prior programming experience required." },
      { q:"What will I learn?", a:"Python, Django, Flask, REST APIs, MySQL, MongoDB, HTML, CSS, JavaScript and React, plus Gen AI integration." },
      { q:"Is Gen AI included?", a:"Yes, prompt engineering and AI tool integration are part of the capstone phase." },
      { q:"How long is the course?", a:"6 months, delivered across structured phases with weekly milestones." },
      { q:"Will I build real projects?", a:"Yes, 10 real-world projects including an e-commerce platform and an AI chatbot." },
      { q:"Is there placement assistance?", a:"Yes, 100% placement assistance with resume building, mock interviews and referral support." },
      { q:"Do I get a certificate?", a:"Yes, an industry recognized, lifetime-valid, project-based certificate." },
      { q:"Is the batch currently open?", a:"Yes, seats are open for the next cohort." }
    ]
  },

  "generative-ai": {
    category: "Artificial Intelligence",
    name: "Generative AI",
    headerLabel: "GENERATIVE AI",
    tagline: "AI Program",
    icon: "🤖",
    duration: "5 Months",
    eligibility: "Any Branch",
    batchStatus: "Batch Open",
    language: "English & Hindi",
    batchStarts: "5th Aug 2026",
    genAI: true,
    headerRating: 4.9,
    headerStudents: "1800+",
    headerPlacement: "100% Placement Assistance",
    projects: "8 Projects",
    level: "Trending",
    price: 65000,
    originalPrice: 129999,
    rating: 4.8,
    reviews: 3560,
    students: 15230,
    badge: "Trending",
    brochure: "generative-ai-brochure",
    certificateImage: "certificates/generative-ai.png",
    description: "Prompt engineering, LLMs, RAG pipelines and multi-agent systems — build with the same tools shaping production AI products today.",
    chips: ["Prompt Engineering", "LLMs", "LangChain", "LangGraph", "OpenAI", "RAG", "Vector Database", "AI Agents", "MCP", "Multi-Agent Systems"],
    jobRoles: ["AI Engineer","LLM Developer","Prompt Engineer","AI Agent Developer","Applied AI Engineer"],
    modules: [
      { title: "LLM Foundations", weeks: "Weeks 1–3", topics: ["How LLMs work", "Prompt engineering patterns", "Tokens, context windows & cost"] },
      { title: "Retrieval-Augmented Generation", weeks: "Weeks 4–7", topics: ["Embeddings & vector databases", "Building a RAG pipeline", "Evaluating retrieval quality"] },
      { title: "Orchestration Frameworks", weeks: "Weeks 8–11", topics: ["LangChain fundamentals", "LangGraph & stateful flows", "Tool calling & function schemas"] },
      { title: "Agents & Protocols", weeks: "Weeks 12–15", topics: ["Designing AI agents", "Multi-agent systems", "Model Context Protocol (MCP)"] },
      { title: "Capstone & Placement Prep", weeks: "Weeks 16–20", topics: ["Production-ready agent project", "Guardrails & safety", "Resume & interview preparation"] }
    ],
    toolsCovered: ["Python","LangChain","LangGraph","OpenAI API","Pinecone","FAISS","Ollama","HuggingFace","Git","GitHub","VS Code","Docker","AWS","Postman"],
    skills: ["Prompt Engineering","LLM Fundamentals","RAG Pipelines","Vector Databases","LangChain","LangGraph","AI Agents","Model Context Protocol","API Integration","Python","Deployment","Problem Solving","Interview Skills"],
    realProjects: [
      { name:"AI Resume Builder", tags:["OpenAI API","React"] },
      { name:"AI Chatbot", tags:["LangChain","Python"] },
      { name:"RAG Knowledge Assistant", tags:["Pinecone","LangChain"] },
      { name:"Multi-Agent Research Tool", tags:["LangGraph","MCP"] },
      { name:"AI Content Generator", tags:["OpenAI API","Prompt Engineering"] },
      { name:"AI Customer Support Bot", tags:["LangChain","FAISS"] },
      { name:"Document Q&A System", tags:["RAG","HuggingFace"] },
      { name:"AI Interview Coach", tags:["OpenAI API","Python"] }
    ],
    faqs: [
      { q:"Who is the Generative AI program for?", a:"Freshers, developers and professionals who want to specialize in LLMs, RAG and AI agents." },
      { q:"Do I need a machine learning background?", a:"No, the course starts from LLM foundations and prompt engineering basics." },
      { q:"What will I learn?", a:"Prompt engineering, RAG pipelines, LangChain, LangGraph, AI agents and the Model Context Protocol." },
      { q:"How long is the course?", a:"5 months, structured across five progressive phases." },
      { q:"Will I build real projects?", a:"Yes, 8 real-world AI projects including a RAG assistant and a multi-agent research tool." },
      { q:"Is there placement assistance?", a:"Yes, 100% placement assistance is included." },
      { q:"Do I get a certificate?", a:"Yes, an industry recognized, project-based certificate." },
      { q:"Is the batch currently open?", a:"Yes, enrollment is open for the next cohort." }
    ]
  },

  "ai-analyst": {
    category: "Data & Analytics",
    name: "AI Analyst",
    headerLabel: "AI ANALYST",
    tagline: "Analytics Program",
    icon: "📊",
    duration: "5 Months",
    eligibility: "Any Branch",
    batchStatus: "Batch Open",
    language: "English & Hindi",
    batchStarts: "12th Aug 2026",
    genAI: true,
    headerRating: 4.7,
    headerStudents: "1100+",
    headerPlacement: "100% Placement Assistance",
    projects: "9 Projects",
    level: "Job Ready",
    price: 65000,
    originalPrice: 129999,
    rating: 4.5,
    reviews: 1780,
    students: 8340,
    badge: "Job Ready",
    brochure: "ai-analyst-brochure",
    certificateImage: "certificates/ai-analyst.png",
    description: "Statistics, machine learning and dashboarding, built around real business questions — from raw data to a decision-ready insight, powered by Gen AI.",
    chips: ["Python", "Power BI", "SQL", "Machine Learning", "Excel", "Statistics", "Business Analytics", "Visualization", "Dashboards"],
    jobRoles: ["AI Analyst","Business Analyst","Data Analyst","Insights Analyst","Reporting Analyst"],
    modules: [
      { title: "Statistics & Excel Foundations", weeks: "Weeks 1–3", topics: ["Descriptive statistics", "Probability basics", "Advanced Excel for analysts"] },
      { title: "SQL for Analysts", weeks: "Weeks 4–6", topics: ["Joins & aggregations", "Window functions", "Query performance"] },
      { title: "Python for Data", weeks: "Weeks 7–11", topics: ["Pandas & NumPy", "Data cleaning at scale", "Intro to machine learning models"] },
      { title: "Visualization & BI", weeks: "Weeks 12–15", topics: ["Power BI dashboards", "Storytelling with data", "Business case studies"] },
      { title: "Capstone & Placement Prep", weeks: "Weeks 16–20", topics: ["AI Integration","End-to-end analytics capstone", "Stakeholder presentation", "Mock interviews"] }
    ],
    toolsCovered: ["Python","Power BI","SQL","Excel","Pandas","NumPy","Git","GitHub","VS Code","Postman","AWS"],
    skills: ["Statistics","SQL","Python for Data","Power BI","Data Cleaning","Machine Learning Basics","Business Analytics","Dashboarding","Prompt Engineering","Problem Solving","Interview Skills"],
    realProjects: [
      { name:"Sales Performance Dashboard", tags:["Power BI","SQL"] },
      { name:"Customer Churn Analysis", tags:["Python","Pandas"] },
      { name:"AI Insights Assistant", tags:["OpenAI API","Python"] },
      { name:"Marketing Campaign Analysis", tags:["Excel","Power BI"] },
      { name:"Inventory Analytics Tool", tags:["SQL","Python"] },
      { name:"HR Attrition Predictor", tags:["Python","Machine Learning"] },
      { name:"Financial Reporting Dashboard", tags:["Power BI","Excel"] },
      { name:"Portfolio Website", tags:["HTML","CSS"] }
    ],
    faqs: [
      { q:"Who is the AI Analyst program for?", a:"Freshers, students and professionals who want a career in analytics and business intelligence." },
      { q:"Do I need a statistics background?", a:"No, the program starts with statistics and Excel foundations." },
      { q:"What will I learn?", a:"Statistics, SQL, Python, Power BI, and applied machine learning for business analytics." },
      { q:"How long is the course?", a:"5 months across five structured phases." },
      { q:"Will I build real projects?", a:"Yes, 9 real-world analytics projects." },
      { q:"Is there placement assistance?", a:"Yes, 100% placement assistance is included." },
      { q:"Do I get a certificate?", a:"Yes, an industry recognized, project-based certificate." },
      { q:"Is the batch currently open?", a:"Yes, enrollment is open." }
    ]
  },

  "data-analyst": {
    category: "Data & Analytics",
    name: "Data Analyst",
    headerLabel: "DATA ANALYST",
    tagline: "Analytics Program",
    icon: "📈",
    duration: "4 Months",
    eligibility: "Any Branch",
    batchStatus: "Batch Open",
    language: "English & Hindi",
    batchStarts: "8th Aug 2026",
    genAI: true,
    headerRating: 4.6,
    headerStudents: "1300+",
    headerPlacement: "100% Placement Assistance",
    projects: "7 Projects",
    level: "High Demand",
    price: 60000,
    originalPrice: 119999,
    rating: 4.6,
    reviews: 2430,
    students: 11020,
    badge: "High Demand",
    brochure: "data-analyst-brochure",
    certificateImage: "certificates/data-analyst.png",
    description: "Excel, SQL, Tableau and Power BI, learned through real business case studies rather than disconnected exercises.",
    chips: ["Python", "SQL", "Excel", "Power BI", "Tableau", "Pandas", "NumPy", "Business Case Studies"],
    jobRoles: ["Data Analyst","Business Intelligence Analyst","Reporting Analyst","Operations Analyst","Insights Analyst"],
    modules: [
      { title: "Excel & Data Fundamentals", weeks: "Weeks 1–2", topics: ["Advanced formulas & pivot tables", "Data cleaning techniques"] },
      { title: "SQL for Business Data", weeks: "Weeks 3–6", topics: ["Writing analytical queries", "Joins, subqueries & CTEs", "Reporting queries"] },
      { title: "Python for Analysis", weeks: "Weeks 7–9", topics: ["Pandas & NumPy fundamentals", "Exploratory data analysis"] },
      { title: "Visualization", weeks: "Weeks 10–13", topics: ["Tableau dashboards", "Power BI dashboards", "Choosing the right chart"] },
      { title: "Capstone & Placement Prep", weeks: "Weeks 14–16", topics: ["Business case study capstone", "Resume & interview preparation", "Mock interviews"] }
    ],
    toolsCovered: ["Excel","SQL","Python","Power BI","Tableau","Pandas","NumPy","Git","GitHub"],
    skills: ["Excel","SQL","Python for Analysis","Tableau","Power BI","Data Cleaning","Business Case Studies","Problem Solving","Interview Skills"],
    realProjects: [
      { name:"Retail Sales Dashboard", tags:["Power BI","SQL"] },
      { name:"Customer Segmentation", tags:["Python","Pandas"] },
      { name:"Supply Chain Analytics", tags:["Tableau","SQL"] },
      { name:"Finance Report Automation", tags:["Excel","Power BI"] },
      { name:"Web Traffic Analysis", tags:["Python","Pandas"] },
      { name:"HR Analytics Dashboard", tags:["Tableau","SQL"] },
      { name:"Portfolio Website", tags:["HTML","CSS"] }
    ],
    faqs: [
      { q:"Who is the Data Analyst program for?", a:"Freshers, students and professionals looking to break into data analytics." },
      { q:"Do I need coding experience?", a:"No, the course starts with Excel fundamentals before moving to SQL and Python." },
      { q:"What will I learn?", a:"Excel, SQL, Python, Tableau and Power BI through real business case studies." },
      { q:"How long is the course?", a:"4 months across five structured phases." },
      { q:"Will I build real projects?", a:"Yes, 7 real-world analytics projects." },
      { q:"Is there placement assistance?", a:"Yes, 100% placement assistance is included." },
      { q:"Do I get a certificate?", a:"Yes, an industry recognized, project-based certificate." },
      { q:"Is the batch currently open?", a:"Yes, enrollment is open." }
    ]
  },

  "data-science": {
    category: "Data & Analytics",
    name: "Data Science",
    headerLabel: "DATA SCIENCE",
    tagline: "Advanced Program",
    icon: "🧠",
    duration: "7 Months",
    eligibility: "Any Branch",
    batchStatus: "Batch Open",
    language: "English & Hindi",
    batchStarts: "15th Aug 2026",
    genAI: true,
    headerRating: 4.8,
    headerStudents: "1400+",
    headerPlacement: "100% Placement Assistance",
    projects: "11 Projects",
    level: "Advanced",
    price: 60000,
    originalPrice: 119999,
    rating: 4.8,
    reviews: 2960,
    students: 10680,
    badge: "Advanced",
    brochure: "data-science-brochure",
    certificateImage: "certificates/data-science.png",
    description: "Deep learning, NLP and computer vision, taken all the way to a deployed, real-world application — not just a notebook.",
    chips: ["Python", "Machine Learning", "Deep Learning", "NLP", "Computer Vision", "TensorFlow", "Scikit Learn", "Data Visualization", "Deployment"],
    jobRoles: ["Data Scientist","Machine Learning Engineer","NLP Engineer","Computer Vision Engineer","AI/ML Developer"],
    modules: [
      { title: "Python & Statistics Foundations", weeks: "Weeks 1–4", topics: ["Python for data science", "Statistics & probability", "Data visualization"] },
      { title: "Machine Learning", weeks: "Weeks 5–10", topics: ["Scikit-Learn fundamentals", "Supervised & unsupervised learning", "Model evaluation & tuning"] },
      { title: "Deep Learning", weeks: "Weeks 11–16", topics: ["Neural networks with TensorFlow", "CNNs for computer vision", "RNNs & sequence models"] },
      { title: "NLP & Applied AI", weeks: "Weeks 17–22", topics: ["Text preprocessing & embeddings", "NLP model fine-tuning", "Applied computer vision projects"] },
      { title: "Capstone & Placement Prep", weeks: "Weeks 23–28", topics: ["End-to-end ML capstone", "Model deployment", "Resume & interview preparation"] }
    ],
    toolsCovered: ["Python","TensorFlow","Scikit Learn","Pandas","NumPy","Git","GitHub","VS Code","Docker","AWS","Postman"],
    skills: ["Python","Statistics","Machine Learning","Deep Learning","NLP","Computer Vision","TensorFlow","Model Deployment","Prompt Engineering","Problem Solving","Interview Skills"],
    realProjects: [
      { name:"Image Classification System", tags:["TensorFlow","CNN"] },
      { name:"Sentiment Analysis Engine", tags:["NLP","Python"] },
      { name:"Recommendation System", tags:["Machine Learning","Python"] },
      { name:"Chatbot with NLP", tags:["NLP","LangChain"] },
      { name:"Fraud Detection Model", tags:["Scikit Learn","Python"] },
      { name:"Object Detection App", tags:["Computer Vision","TensorFlow"] },
      { name:"Stock Price Predictor", tags:["Deep Learning","Python"] },
      { name:"Portfolio Website", tags:["HTML","CSS"] }
    ],
    faqs: [
      { q:"Who is the Data Science program for?", a:"Students and professionals aiming for advanced roles in machine learning and AI." },
      { q:"Do I need prior ML experience?", a:"No, the course builds from Python and statistics foundations before advanced ML and deep learning." },
      { q:"What will I learn?", a:"Machine learning, deep learning, NLP, computer vision and model deployment." },
      { q:"How long is the course?", a:"7 months across five progressive phases." },
      { q:"Will I build real projects?", a:"Yes, 11 real-world ML and AI projects." },
      { q:"Is there placement assistance?", a:"Yes, 100% placement assistance is included." },
      { q:"Do I get a certificate?", a:"Yes, an industry recognized, project-based certificate." },
      { q:"Is the batch currently open?", a:"Yes, enrollment is open." }
    ]
  }

};
