from django.contrib import admin
from . import models

admin.site.register(models.Course)
admin.site.register(models.Enrollment)
admin.site.register(models.Module)
admin.site.register(models.Lesson)
admin.site.register(models.LessonProgress)
admin.site.register(models.PracticeProblem)
admin.site.register(models.PracticeAttempt)
admin.site.register(models.Assignment)
admin.site.register(models.AssignmentSubmission)
admin.site.register(models.Project)
admin.site.register(models.TestAttempt)
admin.site.register(models.Certificate)
admin.site.register(models.JobOpening)
admin.site.register(models.Application)
admin.site.register(models.MockInterview)
admin.site.register(models.CommunityPost)
admin.site.register(models.CommunityComment)
admin.site.register(models.CalendarEvent)
admin.site.register(models.Notification)
admin.site.register(models.Profile)
admin.site.register(models.UserSettings)
